version: "3.8"
services:
  application:
    build:
      dockerfile: ./Dockerfile
    image: application
    container_name: application
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    ports: 
      - 8501:8501
    networks:
      - net

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - 8000:8000
    networks:
      - net

volumes:
  index_data:
    driver: local
  backups:
    driver: local

networks:
  net:
    driver: bridge